tbmq:
  netty:
    port: "${TBMQ_MQTT_PORT:1883}"
    max-connections: "${TBMQ_MAX_CONNECTIONS:10000}"
    boss-threads: "${TBMQ_NETTY_BOSS_THREADS:1}"
    worker-threads: "${TBMQ_NETTY_WORKER_THREADS:0}"
  storage:
    rocksdb:
      path: "${TBMQ_ROCKSDB_PATH:/data/rocksdb}"
  actors:
    throughput: "${TBMQ_ACTOR_THROUGHPUT:10}"
    scheduler-pool-size: "${TBMQ_ACTOR_SCHEDULER_POOL_SIZE:1}"
    max-init-attempts: "${TBMQ_ACTOR_MAX_INIT_ATTEMPTS:10}"
  mqtt:
    max-payload-size: "${TBMQ_MQTT_MAX_PAYLOAD_SIZE:268435456}"
    max-client-id-length: "${TBMQ_MQTT_MAX_CLIENT_ID_LENGTH:128}"
    keep-alive-max: "${TBMQ_MQTT_KEEP_ALIVE_MAX:600}"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: "always"
  metrics:
    enable:
      jvm: true
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: "${TBMQ_HTTP_PORT:8083}"
  shutdown: "graceful"

spring:
  cache:
    type: caffeine
  application:
    name: tbmq-lightweight
  lifecycle:
    timeout-per-shutdown-phase: "10s"
